name: MLflow-CI

on:
  push:
    branches: [ main ]

jobs:
  run-mlflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Miniconda and setup environment
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        activate-environment: mlflow-env        # name di conda.yaml
        environment-file: MLProject/conda.yaml   # path ke file conda.yaml
        python-version: 3.10

    - name: Install pip dependencies as fallback
      run: |
        pip install mlflow
        pip install -r MLProject/requirements.txt

    - name: Run MLflow Project
      run: |
        mlflow run ./MLProject
